server:
  port: ${PORT:8888}
spring:
  application:
      name: config-server
  cloud:
      config:
          server:
              git:
              url: https://github.com/zoezn/BackendII/tree/main/Asincronico/C5/Configs
